spring.application.name=Portfoilio
spring.datasource.url=jdbc:postgresql://${PG_URL}


# uncomment when ready for deployment
#server.port=5000
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}

app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
